"use client";

import React, { useState, useMemo } from "react";
import { useForm, useFieldArray } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { useMutation, useQuery } from "@tanstack/react-query";
import {
  ProjectCreateSchema,
  ProjectUpdateSchema,
  type ProjectCreate,
  type ProjectUpdate,
  slugify,
} from "@rbxfolio/types";
import {
  Input,
  Textarea,
  Select,
  Toggle,
  Heading2,
  Paragraph,
  Caption,
} from "@rbxfolio/design-system";
import { Button } from "@/components/ui/button";

const COMPLETION_OPTIONS = [
  { value: "IN_PROGRESS", label: "In Progress" },
  { value: "COMPLETED", label: "Completed" },
];

const VISIBILITY_OPTIONS = [
  { value: "PRIVATE", label: "Private (Only you can see)" },
  { value: "PUBLIC", label: "Public (Visible in search)" },
];

interface CreateEditProjectFormProps {
  projectId?: string;
  onSuccess?: () => void;
}

/**
 * CreateEditProjectForm Component
 *
 * Form for creating or editing projects with:
 * - Title, descriptions
 * - Auto-generated slug from title
 * - Completion status and visibility
 * - Tag management
 */
export function CreateEditProjectForm({
  projectId,
  onSuccess,
}: CreateEditProjectFormProps) {
  const [autoGeneratedSlug, setAutoGeneratedSlug] = useState("");

  // Fetch existing project if editing
  const { data: project, isLoading: projectLoading } = useQuery({
    queryKey: ["project", projectId],
    queryFn: async () => {
      const res = await fetch(`/api/v1/projects/${projectId}`);
      if (!res.ok) throw new Error("Failed to load project");
      return res.json();
    },
    enabled: !!projectId,
  });

  const validationSchema = projectId ? ProjectUpdateSchema : ProjectCreateSchema;

  const {
    register,
    handleSubmit,
    formState: { errors, isSubmitting },
    watch,
    control,
    reset,
  } = useForm<ProjectCreate | ProjectUpdate>({
    resolver: zodResolver(validationSchema),
    mode: "onBlur",
    defaultValues: project
      ? {
          title: project.title,
          shortDescription: project.shortDescription,
          detailedDescription: project.detailedDescription,
          completionStatus: project.completionStatus,
          visibility: project.visibility,
          tags: project.tags,
        }
      : undefined,
  });

  const { fields: tagFields, append, remove } = useFieldArray({
    control,
    name: "tags" as any,
  });

  // Watch title to auto-generate slug
  const title = watch("title");
  useMemo(() => {
    if (title) {
      setAutoGeneratedSlug(slugify(title));
    }
  }, [title]);

  // Create/update project mutation
  const projectMutation = useMutation({
    mutationFn: async (data: ProjectCreate | ProjectUpdate) => {
      if (projectId) {
        const res = await fetch(`/api/v1/users/me/projects/${projectId}`, {
          method: "PATCH",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(data),
        });
        if (!res.ok) throw new Error("Failed to update project");
        return res.json();
      } else {
        const res = await fetch("/api/v1/users/me/projects", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify(data),
        });
        if (!res.ok) throw new Error("Failed to create project");
        return res.json();
      }
    },
    onSuccess: () => {
      onSuccess?.();
    },
  });

  const onSubmit = (data: ProjectCreate | ProjectUpdate) => {
    projectMutation.mutate(data);
  };

  if (projectLoading) {
    return <Paragraph>Loading project...</Paragraph>;
  }

  return (
    <div className="max-w-4xl mx-auto">
      <Heading2 className="mb-6">
        {projectId ? "Edit Project" : "Create New Project"}
      </Heading2>

      <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
        {/* Basic Information */}
        <div className="space-y-4 p-4 bg-gray-50 rounded-lg">
          <Heading2 className="text-lg">Project Information</Heading2>

          <Input
            label="Project Title"
            placeholder="My Awesome Game"
            error={errors.title?.message}
            {...register("title")}
            required
          />

          {/* Slug Display */}
          {autoGeneratedSlug && (
            <div className="p-3 bg-blue-50 border border-blue-200 rounded-lg">
              <Caption className="text-blue-700">
                Project URL: <code className="font-mono">/projects/{autoGeneratedSlug}</code>
              </Caption>
            </div>
          )}

          <Textarea
            label="Short Description"
            placeholder="One line description of your project"
            error={errors.shortDescription?.message}
            maxLength={300}
            showCharCount
            {...register("shortDescription")}
            required
          />

          <Textarea
            label="Detailed Description"
            placeholder="Full description including features, inspiration, challenges, etc."
            error={errors.detailedDescription?.message}
            maxLength={10000}
            showCharCount
            {...register("detailedDescription")}
          />
        </div>

        {/* Status & Visibility */}
        <div className="space-y-4 p-4 bg-gray-50 rounded-lg">
          <Heading2 className="text-lg">Project Status</Heading2>

          <Select
            label="Completion Status"
            options={COMPLETION_OPTIONS}
            error={errors.completionStatus?.message}
            {...register("completionStatus")}
          />

          <Select
            label="Visibility"
            options={VISIBILITY_OPTIONS}
            error={errors.visibility?.message}
            {...register("visibility")}
          />

          {watch("visibility") === "PUBLIC" && (
            <div className="p-3 bg-green-50 border border-green-200 rounded-lg">
              <Caption className="text-green-700">
                ✓ This project will be visible in search and on your public profile
              </Caption>
            </div>
          )}

          {watch("visibility") === "PRIVATE" && (
            <div className="p-3 bg-yellow-50 border border-yellow-200 rounded-lg">
              <Caption className="text-yellow-700">
                🔒 Only you can see this project. You can change it to public later.
              </Caption>
            </div>
          )}
        </div>

        {/* Tags */}
        <div className="space-y-4 p-4 bg-gray-50 rounded-lg">
          <div className="flex justify-between items-center">
            <Heading2 className="text-lg">Tags (up to 10)</Heading2>
            <Button
              type="button"
              onClick={() => append("")}
              disabled={tagFields.length >= 10}
              className="px-3 py-1 bg-blue-600 text-white rounded text-sm hover:bg-blue-700 disabled:bg-gray-400"
            >
              Add Tag
            </Button>
          </div>

          {tagFields.length === 0 ? (
            <Caption className="text-gray-600">
              Add tags to help people discover your project
            </Caption>
          ) : (
            <div className="space-y-2">
              {tagFields.map((field, index) => (
                <div key={field.id} className="flex gap-2">
                  <Input
                    placeholder="e.g., game, puzzle, multiplayer"
                    {...register(`tags.${index}`)}
                    className="flex-1"
                  />
                  <button
                    type="button"
                    onClick={() => remove(index)}
                    className="px-3 py-2 bg-red-100 text-red-700 rounded hover:bg-red-200 text-sm"
                  >
                    Remove
                  </button>
                </div>
              ))}
            </div>
          )}

          {errors.tags && (
            <Caption className="text-red-500">{errors.tags.message}</Caption>
          )}
        </div>

        {/* Submit */}
        <div className="flex gap-4">
          <Button
            type="submit"
            disabled={isSubmitting || projectMutation.isPending}
            className="px-6 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 disabled:bg-gray-400"
          >
            {projectMutation.isPending
              ? "Saving..."
              : projectId
                ? "Update Project"
                : "Create Project"}
          </Button>

          <Button
            type="button"
            onClick={() => reset()}
            className="px-6 py-2 bg-gray-300 text-gray-900 rounded-lg hover:bg-gray-400"
          >
            Cancel
          </Button>
        </div>

        {projectMutation.isError && (
          <div className="p-4 bg-red-50 border border-red-200 rounded-lg">
            <Caption className="text-red-700">
              Failed to {projectId ? "update" : "create"} project. Please try again.
            </Caption>
          </div>
        )}

        {projectMutation.isSuccess && (
          <div className="p-4 bg-green-50 border border-green-200 rounded-lg">
            <Caption className="text-green-700">
              Project {projectId ? "updated" : "created"} successfully!
            </Caption>
          </div>
        )}
      </form>
    </div>
  );
}
